/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services/web-development'
import { Route as ServicesUiUxDesignRouteImport } from './routes/services/ui-ux-design'
import { Route as ServicesConsultingRouteImport } from './routes/services/consulting'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SrcRoutesServicesGoogleBusinessProfileRouteImport } from './routes/src/routes/services.google-business-profile'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUiUxDesignRoute = ServicesUiUxDesignRouteImport.update({
  id: '/ui-ux-design',
  path: '/ui-ux-design',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesConsultingRoute = ServicesConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const SrcRoutesServicesGoogleBusinessProfileRoute =
  SrcRoutesServicesGoogleBusinessProfileRouteImport.update({
    id: '/src/routes/services/google-business-profile',
    path: '/src/routes/services/google-business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/src/routes/services/google-business-profile': typeof SrcRoutesServicesGoogleBusinessProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/src/routes/services/google-business-profile': typeof SrcRoutesServicesGoogleBusinessProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/ui-ux-design': typeof ServicesUiUxDesignRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/src/routes/services/google-business-profile': typeof SrcRoutesServicesGoogleBusinessProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/services/$slug'
    | '/services/consulting'
    | '/services/ui-ux-design'
    | '/services/web-development'
    | '/src/routes/services/google-business-profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/services/$slug'
    | '/services/consulting'
    | '/services/ui-ux-design'
    | '/services/web-development'
    | '/src/routes/services/google-business-profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/services/$slug'
    | '/services/consulting'
    | '/services/ui-ux-design'
    | '/services/web-development'
    | '/src/routes/services/google-business-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SrcRoutesServicesGoogleBusinessProfileRoute: typeof SrcRoutesServicesGoogleBusinessProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ui-ux-design': {
      id: '/services/ui-ux-design'
      path: '/ui-ux-design'
      fullPath: '/services/ui-ux-design'
      preLoaderRoute: typeof ServicesUiUxDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/consulting': {
      id: '/services/consulting'
      path: '/consulting'
      fullPath: '/services/consulting'
      preLoaderRoute: typeof ServicesConsultingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/src/routes/services/google-business-profile': {
      id: '/src/routes/services/google-business-profile'
      path: '/src/routes/services/google-business-profile'
      fullPath: '/src/routes/services/google-business-profile'
      preLoaderRoute: typeof SrcRoutesServicesGoogleBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesConsultingRoute: typeof ServicesConsultingRoute
  ServicesUiUxDesignRoute: typeof ServicesUiUxDesignRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesConsultingRoute: ServicesConsultingRoute,
  ServicesUiUxDesignRoute: ServicesUiUxDesignRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SrcRoutesServicesGoogleBusinessProfileRoute:
    SrcRoutesServicesGoogleBusinessProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
